### ISSUE TITLE
[CRITICAL] WORKER TIMEOUT

### ISSUE THREAD

**Issue by D0N2k** [a-tal/esi-knife#9]
Hey,

I got the problem that as soon as I run 
`gunicorn --worker-class=gevent --bind=localhost:8888 "esi_knife.web:main()"`

I got this error message. I got it running before but after a restart the worker wont start.
[2018-08-13 16:00:16 +0000] [13893] [INFO] Starting gunicorn 19.4.5
[2018-08-13 16:00:16 +0000] [13893] [INFO] Listening at: http://127.0.0.1:8888 (13893)
[2018-08-13 16:00:16 +0000] [13893] [INFO] Using worker: gevent
[2018-08-13 16:00:16 +0000] [13897] [INFO] Booting worker with pid: 13897
[2018-08-13 16:00:46 +0000] [13893] [CRITICAL] WORKER TIMEOUT (pid:13897)

Do you have an idea?

**Comment by a-tal** [comment]
I can't reproduce this locally, that same command is working fine here.

you say after a restart this stopped working? a restart of your computer?

maybe with more system details I might have an idea of what's going on, it seems like it's probably something local though.

you could try adding `--log-level=DEBUG` to your gunicorn command, it might give you more details for why the worker didn't start. if that doesn't work, maybe try adding `--spew`. it's super ridiculously verbose, but it might point you in the right direction.

**Comment by D0N2k** [comment]
It stopped after restarting my server. Im running it within a screen session. 

Im running a server on 16.04.5 LTS.

Debug output:
```[29965] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f49c2853f50>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: gevent
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f49c2853c80>
  pre_fork: <function pre_fork at 0x7f49c2853de8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 0
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 1
  proc_name: None
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f49c2853b18>
  pre_exec: <function pre_exec at 0x7f49c2842578>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f49c2842140>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f49c2842c08>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f49c28426e0>
  post_request: <function post_request at 0x7f49c28427d0>
  user: 0
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f49c28422a8>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f49c2842938>
  chdir: /home/dclemens
  paste: None
  default_proc_name: esi_knife.web:main()
  errorlog: -
  loglevel: DEBUG
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f49c28539b0>
  worker_abort: <function worker_abort at 0x7f49c2842410>
  bind: ['localhost:8888']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f49c2842aa0>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix:
[2018-08-13 22:37:50 +0000] [29965] [INFO] Starting gunicorn 19.4.5
[2018-08-13 22:37:50 +0000] [29965] [DEBUG] Arbiter booted
[2018-08-13 22:37:50 +0000] [29965] [INFO] Listening at: http://127.0.0.1:8888 (29965)
[2018-08-13 22:37:50 +0000] [29965] [INFO] Using worker: gevent
[2018-08-13 22:37:50 +0000] [29969] [INFO] Booting worker with pid: 29969
[2018-08-13 22:37:50 +0000] [29965] [DEBUG] 1 workers
[2018-08-13 22:38:20 +0000] [29965] [CRITICAL] WORKER TIMEOUT (pid:29969)
[2018-08-13 22:38:20 +0000] [29969] [INFO] Worker exiting (pid: 29969)
[2018-08-13 22:38:20 +0000] [29997] [INFO] Booting worker with pid: 29997
^C[2018-08-13 22:38:21 +0000] [29965] [INFO] Handling signal: int
[2018-08-13 22:38:21 +0000] [29997] [INFO] Worker exiting (pid: 29997)
[2018-08-13 22:38:21 +0000] [29965] [INFO] Shutting down: Master```

**Comment by a-tal** [comment]
interesting. so we know that:

- you're able to bind to the port successfully, nothing else is (could confirm with `sudo netstat -nalp | grep -E '^tcp.*:8888.*LISTEN'`), you'd get an error message sooner if this was the case
- gunicorn, gevent and all dependancies are installed (including paths, etc), b/c the gunicorn worker has started at least


couple questions:

- is there some existing `redis` that resolves locally? if so you'll want to set up credentials/config for that via these env vars: https://github.com/a-tal/esi-knife/blob/master/esi_knife/__init__.py#L35-L71
- can the server make https calls to `esi.evetech.net`? it could maybe stall out on init if requests to this url were being black hole'd


if your answers are 'no' then 'yes': what version of python is this, are we in a virtualenv? I might have to try to create a Dockerfile replicating your setup to repro. might need your `pip freeze` output as well

**Comment by a-tal** [comment]
actually, try the cli (`knife`). I suspect it might be an issue with your python/requests/ssl. if so the cli would error as well, maybe in a more verbose fashion.

**Comment by a-tal** [comment]
if this is python3.7 this could be related to https://github.com/gevent/gevent/issues/1260

**Comment by D0N2k** [comment]
Hey,

yes redis ist installed. I will try to set it up. :) . the https calls shouldn't be a problem. Im running a pathfinder and a seat installation on this server too. 

Pip wont install the cli. 

Those are my python versions:
python -V
Python 2.7.12
/usr/bin/python3 -V
Python 3.5.2

**Comment by D0N2k** [comment]
*facepalm* sorry I just changed the redis value that you pointed out. (redis to 127.0.0.1) and now its working fine. Thanks for your patience

**Comment by a-tal** [comment]
cool beans, glad you got it sorted
